In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
#import titanic file 
titanic_data = pd.read_csv('data/titanic.csv')
titanic_data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [3]:
titanic_data.describe()

         Survived      Pclass         Age       SibSp        PaCh       Fare
count  887.000000  887.000000  887.000000  887.000000  887.000000  887.00000
mean     0.385569    2.305524   29.471443    0.525366    0.383315   32.30542
std      0.487004    0.836662   14.121908    1.104669    0.807466   49.78204
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.00000
25%      0.000000    2.000000   20.250000    0.000000    0.000000    7.92500
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.45420
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.13750
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.32920